services:
  ms-sql-server:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ./Database/mssql:/var/opt/mssql
      - ./Database/init:/docker-entrypoint-initdb.d/init
    environment:
      MSSQL_SA_PASSWORD: RootPass1!
      ACCEPT_EULA: Y